# Generated by Django 5.2.8 on 2025-11-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
        ('GestionProduits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.produit')),
            ],
        ),
    ]
