# Generated by Django 5.2.8 on 2025-11-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
        ('GestionProduits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Commercant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authentification.commercant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.categorie'),
            preserve_default=False,
        ),
    ]
