# Generated by Django 5.2.8 on 2026-01-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_utilisateur_image'),
        ('Commande', '0001_initial'),
        ('GestionProduits', '0002_produit_commercant_id_produit_categorie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Authentification.client'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours de traitement'), ('preparee', 'Préparée'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=50),
        ),
        migrations.CreateModel(
            name='ArticleCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='Commande.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GestionProduits.produit')),
            ],
            options={
                'verbose_name': 'Article Commande',
                'verbose_name_plural': 'Articles Commande',
            },
        ),
    ]
