# Generated by Django 5.2.8 on 2025-11-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
        ('GestionProduits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('note', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.produit')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AvisCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.client')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.commercant')),
            ],
            options={
                'verbose_name': 'Avis Commerçant',
                'verbose_name_plural': 'Avis Commerçants',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.client')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.commercant')),
            ],
            options={
                'verbose_name': 'Commentaire Commerçant',
                'verbose_name_plural': 'Commentaires Commerçants',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseCommentaireCommercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='Publication.commentairecommercant')),
                ('commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.commercant')),
            ],
            options={
                'verbose_name': 'Réponse Commentaire Commerçant',
                'verbose_name_plural': 'Réponses Commentaires Commerçants',
                'ordering': ['-date_creation'],
            },
        ),
    ]
