# Generated by Django 5.2.8 on 2025-12-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_utilisateur_image'),
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviscommercant',
            name='client',
        ),
        migrations.RemoveField(
            model_name='aviscommercant',
            name='commercant',
        ),
        migrations.RemoveField(
            model_name='commentairecommercant',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commentairecommercant',
            name='commercant',
        ),
        migrations.RemoveField(
            model_name='reponsecommentairecommercant',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='reponsecommentairecommercant',
            name='commercant',
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.commercant')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='AvisCommercant',
        ),
        migrations.DeleteModel(
            name='CommentaireCommercant',
        ),
        migrations.DeleteModel(
            name='ReponseCommentaireCommercant',
        ),
    ]
