# Generated by Django 5.2.8 on 2025-11-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
        ('Commande', '0001_initial'),
        ('GestionProduits', '0001_initial'),
        ('Livraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.categorie')),
            ],
            options={
                'verbose_name': 'Notification Categorie',
                'verbose_name_plural': 'Notifications Categories',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commande.commande')),
            ],
            options={
                'verbose_name': 'Notification Commande',
                'verbose_name_plural': 'Notifications Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livraison.livraison')),
            ],
            options={
                'verbose_name': 'Notification Livraison',
                'verbose_name_plural': 'Notifications Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.produit')),
            ],
            options={
                'verbose_name': 'Notification Produit',
                'verbose_name_plural': 'Notifications Produits',
                'ordering': ['-date_creation'],
            },
        ),
    ]
