# Generated by Django 5.2.8 on 2026-01-03 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_utilisateur_image'),
        ('Commande', '0002_commande_adresse_livraison_and_more'),
        ('Paiement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='devise',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='paiement',
            name='message_erreur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Authentification.client'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='Commande.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En Cours'), ('confirme', 'Confirmé'), ('effectue', 'Effectué'), ('echec', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('carte', 'Carte Bancaire'), ('paypal', 'PayPal'), ('virement', 'Virement'), ('autre', 'Autre')], default='carte', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('commande',)},
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('statut_avant', models.CharField(max_length=50)),
                ('statut_apres', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='Paiement.paiement')),
            ],
            options={
                'verbose_name': 'Historique Paiement',
                'verbose_name_plural': 'Historiques Paiements',
                'ordering': ['-date'],
            },
        ),
    ]
