# Generated by Django 5.2.8 on 2025-11-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
        ('GestionProduits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('date_livraison', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En Cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_cours', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.client')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.livreur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentification.client')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Livraison.livraison')),
            ],
            options={
                'verbose_name': 'Évaluation Livraison',
                'verbose_name_plural': 'Évaluations Livraisons',
                'ordering': ['livraison__date_livraison'],
            },
        ),
        migrations.CreateModel(
            name='DetailLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_de_livraison', models.DecimalField(decimal_places=0, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.produit')),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Livraison.livraison')),
            ],
            options={
                'verbose_name': 'Détail Livraison',
                'verbose_name_plural': 'Détails Livraisons',
                'ordering': ['livraison__date_livraison'],
            },
        ),
    ]
