# Generated by Django 5.2.8 on 2025-12-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commande', '0001_initial'),
        ('GestionProduits', '0002_produit_commercant_id_produit_categorie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=50),
        ),
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Commande.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionProduits.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['-commande__date_commande'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(related_name='commandes', through='Commande.CommandeItem', to='GestionProduits.produit'),
        ),
    ]
